app:
  build: .
  command: bash -c "rails server Puma -p 3000 -b '0.0.0.0' && bundle exec ./bin/webpack-dev-server"
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
    - redis
  env_file: config/app.env
postgres:
  image: postgres:9.4
  ports:
    - "5435:5432"
  volumes_from:
    - db-data
  env_file: config/db.env
db-data:
  image: postgres:9.4
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - /var/lib/postgresql/data
redis:
  image: redis
  ports:
    - "6379:6379"
sidekiq:
  build: .
  volumes:
    - .:/app
  links:
    - postgres
    - redis
  command: sidekiq -L log/sidekiq.log
  env_file: config/app.env
