auth:
  google:
    enable: '1'
    client_id: ''
    client_secret: ''
  facebook:
    enable: '1'
    facebook_key: ''
    facebook_secret: ''
  twitter:
    enable: '1'
    consumer_key: ''
    consumer_secret: ''
domain: ''