signaled_matching_with_blocked_account: true
signaled_matching_with_suspected_account: true
considered_email_similar_when_x_characters: 2
considered_username_similar_when_x_characters: 2
signaled_matching_with_suspected_account: true
max_username_renew: 3
min_username_character: 3
min_password_character: 8
removal_delay_duration: 20 # nil if we want to keep removed users in database
is_suspect_user_removable: false # false ensure this pseudo won't be used again & similars new accounts will be signaled to admin
is_blocked_user_removable: false # same as above
